FROM node:12-alpine

ARG encryption_key=the_key_come_from_docker_build_cmd_line
ARG node_env=development
ENV ENCRYPTION_KEY=$encryption_key
ENV NODE_ENV=$node_env

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .

# Run the image as a non-root user
# RUN adduser -D web_user
# USER web_user

EXPOSE 3000
CMD [ "node", "src/server.js" ]
